version: 2
updates:
- package-ecosystem: nuget
  directory: "/chapter5"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Polly
    versions:
    - 7.2.1
